from aiogram.filters.state import State, StatesGroup
from aiogram.fsm.context import FSMContext

class Form(StatesGroup):
    Text_VisualQR = State()
    Image_VisualQR = State()
    set_qr = State()
    set_bg_color =State()
    # set_color_bg = State()
    set_background = State()
    set_foreground = State()
    set_light = State()
    set_data_dark = State()
    set_data_light = State()
    set_advance_image = State()   
    set_alignment_dark = State()
    set_alignment_light = State()
    set_finder_dark = State()
    set_finder_light = State()
    set_quiet_zone = State()
    set_timing_dark =State()
    set_timing_light = State()
    set_version_dark = State()
    set_version_light = State()
    set_separator = State()
    qr_custom = State()
    set_image = State()
    set_message = State()
    set_location = State()
    set_repair = State()
    set_color = State()
    set_ads = State()
    set_prompt = State()
    set_format_dark = State()
    set_format_light = State()
    set_place_ads = State()